{"timestamp":"2025-10-14T18:37:53.273388Z","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-14T18:37:53.273816Z","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/ETL_toll_data_python.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-14T18:37:53.306537Z","level":"info","event":"Task instance is in running state","logger":"task.stdout"}
{"timestamp":"2025-10-14T18:37:53.306724Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","logger":"task.stdout"}
{"timestamp":"2025-10-14T18:37:53.306819Z","level":"info","event":"Current task name:extract_tsv","logger":"task.stdout"}
{"timestamp":"2025-10-14T18:37:53.306885Z","level":"info","event":"Dag name:ETL_toll_data_python","logger":"task.stdout"}
{"timestamp":"2025-10-14T18:37:53.310487Z","level":"error","event":"Task failed with exception","logger":"task","filename":"task_runner.py","lineno":994,"error_detail":[{"exc_type":"FileNotFoundError","exc_value":"[Errno 2] No such file or directory: 'output/tsv_data.csv'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1307,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":82,"name":"run"},{"filename":"/opt/airflow/dags/ETL_toll_data_python.py","lineno":58,"name":"extract_tsv_data"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py","lineno":948,"name":"read_csv"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py","lineno":611,"name":"_read"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py","lineno":1448,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py","lineno":1705,"name":"_make_engine"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py","lineno":863,"name":"get_handle"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-10-14T18:37:53.326654Z","level":"info","event":"Task instance in failure state","logger":"task.stdout"}
{"timestamp":"2025-10-14T18:37:53.326896Z","level":"info","event":"Task start","logger":"task.stdout"}
{"timestamp":"2025-10-14T18:37:53.326984Z","level":"info","event":"Task:<Task(PythonOperator): extract_tsv>","logger":"task.stdout"}
{"timestamp":"2025-10-14T18:37:53.327045Z","level":"info","event":"Failure caused by [Errno 2] No such file or directory: 'output/tsv_data.csv'","logger":"task.stdout"}
